fix variable
with curly braces, led to terminal error with copy-paste:
```
kubectl apply --server-side --force-conflicts -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v$\{GWAPI_VERSION\}/standard-install.yaml
error: unable to read URL "https://github.com/kubernetes-sigs/gateway-api/releases/download/v$%7BGWAPI_VERSION%7D/standard-install.yaml", server reported 404 Not Found, status code=404
```

Signed-off-by: Art Berger <art.berger@solo.io>