bump Hugo version
older Hugo version was causing build to fail with new reuse-append shortcode:
Error: error building site: "/opt/buildhome/repo/content/docs/llm/providers/azure.md:25:1": failed to render shortcode "tabs": "/opt/buildhome/repo/content/docs/llm/providers/azure.md:1:1": failed to render shortcode "tab": "/opt/buildhome/repo/content/docs/llm/providers/azure.md:1:1": failed to render shortcode "reuse-append": failed to process shortcode: "/opt/buildhome/repo/layouts/shortcodes/reuse-append.html:15:28": execute of template failed: template: shortcodes/reuse-append.html:15:28: executing "shortcodes/reuse-append.html" at <strings>: can't evaluate field TrimSpace in type interface {}

see Slack: https://solo-io-corp.slack.com/archives/CHJV572TG/p1759444221332239

Signed-off-by: Art Berger <art.berger@solo.io>